### ISSUE TITLE
Relation information does not save

### ISSUE THREAD

**Issue by slavenIBE** [yesiman/INRAE.VINEAS#13]
After signed in to my personal profile on VINEAS, I go to MY DASHBOARD. I am trying to connect the ADAPT2CLIMA project to the IBE personal profile but after selecting the relation between IBE and ADAPT2CLIMA and clicking save it does not save.

I would like to whoever sees the IBE - Istituto per la BioEconomia profile page can see that the ADAPT2CLIMA project is related to the institute, because for now the only related project is MEDCLIV.

I cannot find where the issue is.

**Comment by yesiman** [comment]
When you say that it did not save, the popup closed well after validation? On ADAPT2CLIMA, IBE was properly linked, on IBE i add the ADAPT2CLIMA project and relations seems to be ok to. Can you check it ?

**Comment by slavenIBE** [comment]
Now it is visible on the profile page under the RESEAU option but it is not visible when you click the LIST option (images below). Whenever I clicked the SAVE button and tried to close the operation, a popup message would appear saying "The content was not saved. Do you wish to continue? Y N"

I tried a couple of times and it appeared again after which I wrote in GitHub to get the answer.

RESEAU
![immagine](https://user-images.githubusercontent.com/77341538/104451084-5d661980-55a1-11eb-9be1-93350fccb87c.png)

LISTE (Page 1 of 2)
![immagine](https://user-images.githubusercontent.com/77341538/104451103-622acd80-55a1-11eb-9dbb-3ce7e27776c0.png)

LISTE (Page 2 of 2)
![immagine](https://user-images.githubusercontent.com/77341538/104451112-6525be00-55a1-11eb-9c8b-5a95c9f40194.png)

**Comment by yesiman** [comment]
When you click on the "save" button, the popup should close after a second or two, is ther a loader when you click on save ? you don't have to "close the operation" this could cancel the save.

**Comment by slavenIBE** [comment]
There was no loader when I clicked SAVE. It remained still after multiple clicks.

**Comment by MaddyTintinger** [comment]
It is strange because I can see Adapt2clima linked with IBE (in the network map and in the list) but I cannot see FEM, neither in the network map nor in the list. There is no difference between page 1 and 2 in the "LISTE". I don't see FEM as a related actor for IBE in the dashboard. @slavenIBE do you see FEM as a related actor of IBE in your dashboard? 
![image](https://user-images.githubusercontent.com/72983752/104472724-88119b80-55bc-11eb-8a94-4e190d67a175.png)
![image](https://user-images.githubusercontent.com/72983752/104472739-8cd64f80-55bc-11eb-9a58-32e18adee95a.png)

@yesiman C'est bizarre car je ne vois pas de relation entre FEM et IBE dans le BO alors que FEM s'affiche la liste de Slaven, à la place de ADAPT2CLIMA. Il ne devrait pas y avoir 2 pages dans la liste car 4 éléments liés sur la carte des relations... Les screens sont fait quand je ne suis pas connectée

**Comment by slavenIBE** [comment]
@MaddyTintinger I do not see FEM's relation on our profile page. The only way we are connected as far as I can see in the NETWORK MAP is through our connection to CAVIRO. Theres seem to be a lot of discrepancies in the relational mapping as it does not universally change for ALL the elements that are in VINEAS but rather a step by step approach in resolving singular elements that I have not honestly mastered as evidenced by my writing in GitHub about the problem.

**Comment by MaddyTintinger** [comment]
Hi @slavenIBE, This porblem has been solved, can you close this issue please ?
