### ISSUE TITLE
Events: automatic shift to English + missing date & place

### ISSUE THREAD

**Issue by eccele** [yesiman/INRAE.VINEAS#43]
In the "events" the dates are not displayed in the Agenda: this is a very important information to be seen together with the title and image of the event... Also the place should be shown at once.

[the problem with the language (see below) has not occurred any longer]

**Comment by MaddyTintinger** [comment]
I think it automatically shifts to English because you enter the event with the "current version" in English and not in Italian... 

What do you mean by "the dates are not displayed in the Agenda". That we can not see the date when we are on "coming events" ?  I think that if people are interesting, they will click on the event and then see the date.

**Comment by eccele** [comment]
Please, try to select the language "Italian" and open the "News" I wrote
lately on the presentation of VINEAS for Italy: when I open the page, the
language is English.

Concerning date and place: I think it is really important that they are
visible without needing to click on the object, this is a sort of standard
for the publication of events...

Emanuele Eccel


Centro Ricerca e Innovazione - http://www.fmach.it/CRI

Fondazione Edmund Mach

Via Mach, 1 - 38098 S. Michele all'Adige (TN) - Italy
T: + 39 0461-615397

Skype: emanuele.eccel

*"Il mondo non languirà mai per mancanza di cose meravigliose, ma solo per
mancanza di meraviglia.*” *(G.K. Chesterton)*


Il giorno gio 11 mar 2021 alle ore 10:20 MaddyTintinger <
***@***.***> ha scritto:
